# .github/release-drafter.yml
name-template: '$RESOLVED_VERSION'  # Removed v prefix
tag-template: '$RESOLVED_VERSION'   # Removed v prefix

template: |
  ## Changes in this Release
  
  $CHANGES
  
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_VERSION

categories:
  - title: '🚀 Features'
    label: 'feature'
  - title: '🐛 Bug Fixes'
    label: 'fix'
  - title: '🧰 Maintenance'
    label: 'chore'
  - title: '📚 Documentation'
    label: 'documentation'

autolabeler:
  - label: 'feature'
    branch:
      - '/feat\/.+/'
    title:
      - '/feat:/i'
  - label: 'fix'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix:/i'
  - label: 'chore'
    branch:
      - '/chore\/.+/'
    title:
      - '/chore:/i'
  - label: 'documentation'
    branch:
      - '/docs?\/.+/'
    title:
      - '/docs?:/i'

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'chore'
      - 'dependencies'
      - 'documentation'
  default: patch

commitish: master  # Changed from main to master
exclude-labels:
  - 'skip-changelog'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
no-changes-template: '* No changes'