name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
template: |
  ## What's Changed
  $CHANGES
  
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
  
  ## Installation
  ```bash
  npm install your-package-name@$RESOLVED_VERSION
  ```

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
      - 'docs'

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'chore'
      - 'dependencies'
      - 'documentation'
  default: patch

exclude-labels:
  - 'skip-changelog'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

replacers:
  - search: '/CVE-(\d{4})-(\d+)/g'
    replace: 'CVE-$1-$2'